In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [2]:
filename = 'data.csv'
df = pd.read_csv(filename)

In [3]:
df

          qs1       qs2       qs3       qs4       qs5     merge  partition
0    0.005522  0.005188  0.004903  0.004289  0.005724  0.005185   0.006342
1    0.003576  0.005012  0.004359  0.004156  0.004296  0.004609   0.003650
2    0.003432  0.004460  0.004154  0.004168  0.004313  0.004664   0.003627
3    0.003521  0.004704  0.004661  0.004121  0.003940  0.004553   0.003768
4    0.003419  0.004490  0.004440  0.004394  0.003951  0.004564   0.003578
..        ...       ...       ...       ...       ...       ...        ...
595  0.003546  0.006327  0.005415  0.004580  0.004667  0.004450   0.003492
596  0.003402  0.004711  0.004244  0.003888  0.004024  0.006439   0.004926
597  0.003952  0.004659  0.004431  0.004100  0.003957  0.004851   0.003551
598  0.003235  0.004860  0.004812  0.004062  0.003908  0.004518   0.003678
599  0.003499  0.004504  0.004692  0.004114  0.004295  0.004487   0.003718

[600 rows x 7 columns]

In [4]:
anova = stats.f_oneway(df['qs1'], df['qs2'], df['qs3'],
                        df['qs4'], df['qs5'], df['merge'], df['partition'])
print(anova)
if anova.pvalue < 0.05:
    print("anova p-value is:", anova.pvalue)
    print("With p < 0.05, we conclude that there is a differnce between the means of run time of different sorting funtions.")
    print("Post Hoc Analysis:")
    melt = pd.melt(df)
    posthoc = pairwise_tukeyhsd(
        melt['value'], melt['variable'],
        alpha=0.05)
    print(posthoc)

F_onewayResult(statistic=393.08065577390744, pvalue=0.0)
anova p-value is: 0.0
With p < 0.05, we conclude that there is a differnce between the means of run time of different sorting funtions.
Post Hoc Analysis:
   Multiple Comparison of Means - Tukey HSD, FWER=0.05
==========================================================
  group1    group2  meandiff p-adj   lower   upper  reject
----------------------------------------------------------
    merge partition   -0.001  0.001 -0.0011 -0.0009   True
    merge       qs1  -0.0011  0.001 -0.0012  -0.001   True
    merge       qs2     -0.0 0.7185 -0.0001     0.0  False
    merge       qs3  -0.0001  0.001 -0.0002 -0.0001   True
    merge       qs4  -0.0005  0.001 -0.0006 -0.0004   True
    merge       qs5  -0.0005  0.001 -0.0006 -0.0004   True
partition       qs1  -0.0001 0.0052 -0.0002    -0.0   True
partition       qs2   0.0009  0.001  0.0009   0.001   True
partition       qs3   0.0008  0.001  0.0008  0.0009   True
partition       qs4   0.0005  0.001  0.0004  0.0006   True
partition       qs5   0.0005  0.001  0.0004  0.0006   True
      qs1       qs2   0.0011  0.001   0.001  0.0012   True
      qs1       qs3    0.001  0.001  0.0009  0.0011   True
      qs1       qs4   0.0006  0.001  0.0005  0.0007   True
      qs1       qs5   0.0006  0.001  0.0005  0.0007   True
      qs2       qs3  -0.0001 0.0247 -0.0002    -0.0   True
      qs2       qs4  -0.0005  0.001 -0.0006 -0.0004   True
      qs2       qs5  -0.0005  0.001 -0.0006 -0.0004   True
      qs3       qs4  -0.0004  0.001 -0.0005 -0.0003   True
      qs3       qs5  -0.0004  0.001 -0.0005 -0.0003   True
      qs4       qs5     -0.0    0.9 -0.0001  0.0001  False
----------------------------------------------------------