In [1]:
import time
import numpy as np
import pandas as pd
import scipy.stats as stats

from implementations import all_implementations

In [2]:
data = pd.DataFrame(
                    columns=['qs1','qs2','qs3','qs4',
                             'qs5','merge','partition'],dtype=float
                    )

In [3]:
for i in range (600):
    test_result = []
    random_array = np.random.randint(0,500,size=(500))
    for sort in all_implementations:
        st = time.time()
        res = sort(random_array)
        en = time.time()
        test_result.append(en-st)

    data.loc[len(data), :] = test_result
    test_result.clear()

In [4]:
data.to_csv('data.csv',index=False)
data

          qs1       qs2       qs3       qs4       qs5     merge  partition
0    0.005522  0.005188  0.004903  0.004289  0.005724  0.005185   0.006342
1    0.003576  0.005012  0.004359  0.004156  0.004296  0.004609   0.003650
2    0.003432  0.004460  0.004154  0.004168  0.004313  0.004664   0.003627
3    0.003521  0.004704  0.004661  0.004121  0.003940  0.004553   0.003768
4    0.003419  0.004490  0.004440  0.004394  0.003951  0.004564   0.003578
..        ...       ...       ...       ...       ...       ...        ...
595  0.003546  0.006327  0.005415  0.004580  0.004667  0.004450   0.003492
596  0.003402  0.004711  0.004244  0.003888  0.004024  0.006439   0.004926
597  0.003952  0.004659  0.004431  0.004100  0.003957  0.004851   0.003551
598  0.003235  0.004860  0.004812  0.004062  0.003908  0.004518   0.003678
599  0.003499  0.004504  0.004692  0.004114  0.004295  0.004487   0.003718

[600 rows x 7 columns]